flags: {}
packages:
- .
extra-deps:
- conduit-1.2.13.1
- conduit-extra-1.2.3.2
- fay-0.23.2.0
- fay-base-0.20.0.1
- fay-dom-0.5.0.1
- haskell-src-exts-1.19.1
- persistent-2.7.3.1
- resourcet-1.1.11
- spoon-0.3.1
- yesod-core-1.4.37.3
- yesod-form-1.4.16
- yesod-persistent-1.4.3
- yesod-static-1.5.3.1
resolver: lts-11.1
